# Generated by Django 2.1.7 on 2019-03-19 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FvAEPg',
            fields=[
                ('apic_addr', models.CharField(max_length=200)),
                ('pcEnfPref', models.CharField(max_length=200)),
                ('dn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=200)),
                ('tenant', models.CharField(default='none', max_length=200)),
                ('bd_tDn', models.CharField(max_length=200)),
                ('fvRsDomAtt_tDn', models.CharField(max_length=200)),
                ('fvRsPathAtt', models.CharField(max_length=200)),
                ('fvRsCons', models.CharField(max_length=200)),
                ('fvRsProv', models.CharField(max_length=200)),
                ('modTs', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FvBD',
            fields=[
                ('apic_addr', models.CharField(max_length=200)),
                ('descr', models.CharField(max_length=200)),
                ('dn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('arpFlood', models.CharField(max_length=200)),
                ('epMoveDetectMode', models.CharField(max_length=200)),
                ('ipLearning', models.CharField(max_length=200)),
                ('limitIpLearnToSubnets', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('unicastRoute', models.CharField(max_length=200)),
                ('unkMacUcastAct', models.CharField(max_length=200)),
                ('unkMcastAct', models.CharField(max_length=200)),
                ('fvSubnet1', models.CharField(default='none', max_length=200)),
                ('fvSubnet1_scope', models.CharField(default='none', max_length=200)),
                ('fvSubnet2', models.CharField(default='none', max_length=200)),
                ('fvSubnet2_scope', models.CharField(default='none', max_length=200)),
                ('fvSubnet3', models.CharField(default='none', max_length=200)),
                ('fvSubnet3_scope', models.CharField(default='none', max_length=200)),
                ('fvRsCtx', models.CharField(default='none', max_length=200)),
                ('fvRsBDToOut1', models.CharField(default='none', max_length=200)),
                ('fvRsBDToOut2', models.CharField(default='none', max_length=200)),
                ('fvRsBDToOut3', models.CharField(default='none', max_length=200)),
                ('modTs', models.CharField(default='none', max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
