# Generated by Django 2.1.7 on 2019-03-20 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nxos_vlan_svi',
            fields=[
                ('encap', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=200)),
                ('svi_ip', models.CharField(default='none', max_length=200)),
                ('vrf', models.CharField(default='none', max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
