# Generated by Django 2.1.7 on 2019-03-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0003_nxos_vlan_svi_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fvaepg',
            name='encap',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='fvaepg',
            name='legacy_switch',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='fvaepg',
            name='dn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fvaepg',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
