# Generated by Django 2.1.7 on 2019-03-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0004_auto_20190321_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fvaepg',
            name='vrf',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
