# Generated by Django 2.1.7 on 2019-03-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0005_fvaepg_vrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpgInputForm',
            fields=[
                ('apic_addr', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('default_tenant', models.CharField(max_length=200)),
                ('default_ipg_name', models.CharField(max_length=200)),
                ('physical_domain', models.CharField(max_length=200)),
            ],
        ),
    ]
