# Generated by Django 2.1.7 on 2019-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0006_epginputform'),
    ]

    operations = [
        migrations.AddField(
            model_name='epginputform',
            name='migration_leafs_nodeid',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
