# Generated by Django 2.1.7 on 2019-03-22 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0008_auto_20190322_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectConfigurationStatus',
            fields=[
                ('object_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('object_configuration', models.TextField()),
                ('post_status', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='epginputform',
            name='apic_addr',
            field=models.GenericIPAddressField(default='192.168.0.1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='epginputform',
            name='default_ipg_name',
            field=models.CharField(default='LEGACY-NEXUS-VPC_IPG', max_length=200),
        ),
        migrations.AlterField(
            model_name='epginputform',
            name='default_tenant',
            field=models.CharField(default='LEGACY-TENANT-TN', max_length=200),
        ),
        migrations.AlterField(
            model_name='epginputform',
            name='physical_domain',
            field=models.CharField(default='LEGACY_PHY', max_length=200),
        ),
    ]
