# Generated by Django 2.1.7 on 2019-03-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0009_auto_20190322_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectconfigurationstatus',
            name='post_url',
            field=models.URLField(default='none'),
        ),
    ]
