# Generated by Django 2.1.7 on 2019-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0010_objectconfigurationstatus_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fvaepg',
            name='fvRsCons',
        ),
        migrations.RemoveField(
            model_name='fvaepg',
            name='fvRsProv',
        ),
        migrations.AddField(
            model_name='fvaepg',
            name='fvSubnet',
            field=models.GenericIPAddressField(default='none'),
        ),
        migrations.AddField(
            model_name='fvaepg',
            name='mode',
            field=models.CharField(default='l2', max_length=2),
        ),
        migrations.AddField(
            model_name='fvaepg',
            name='vzAny',
            field=models.CharField(default='yes', max_length=3),
        ),
    ]
