# Generated by Django 2.1.7 on 2019-03-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0012_auto_20190325_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fvbd',
            name='fvSubnet1',
            field=models.CharField(max_length=200),
        ),
    ]
