# Generated by Django 2.2.2 on 2019-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxos_config_import', '0015_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fvaepg',
            name='apic_addr',
        ),
        migrations.RemoveField(
            model_name='fvbd',
            name='apic_addr',
        ),
        migrations.AlterField(
            model_name='epginputform',
            name='apic_addr',
            field=models.GenericIPAddressField(default='sandboxapicdc.cisco.com', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pushdataapic',
            name='apic_addr',
            field=models.CharField(default='sandboxapicdc.cisco.com', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pushdataapic',
            name='password',
            field=models.CharField(default='ciscopsdt', max_length=200),
        ),
    ]
